package reega.data;

import java.io.IOException;
import java.sql.SQLException;

import reega.data.models.UserAuth;
import reega.users.GenericUser;
import reega.users.NewUser;

/**
 * This controller handles all the operations on users and authentication
 */
public interface AuthController {
    /**
     * Add user to REEGA platform
     *
     * @param newUser
     * @throws SQLException
     */
    void addUser(NewUser newUser) throws SQLException, IOException;

    /**
     * Login using email and password
     *
     * @param email
     * @param password the password's hash generated by AES.encrypt method
     * @return the user if login succeeded or null if email not found or wrong
     * password
     * @throws SQLException
     * @See GenericUser
     */
    GenericUser emailLogin(String email, String password) throws SQLException, IOException;

    /**
     * Login using fiscal code and password
     *
     * @param fiscalCode ths user's fiscal code
     * @param password   the password's hash generated by AES.encrypt method
     * @return the user if login succeeded or null if fiscal code not found or wrong
     * password
     * @throws SQLException
     */
    GenericUser fiscalCodeLogin(String fiscalCode, String password) throws SQLException, IOException;

    /**
     * Login using the credentials locally stored
     *
     * @param credentials
     * @return
     */
    GenericUser tokenLogin(UserAuth credentials) throws SQLException, IOException;

    /**
     * Store selector and validator to enable the remind-me functionality
     *
     * @param selector  random aphanumrical string up to 12 characters
     * @param validator SHA256 encryption of a random alphanumerical string (64
     *                  characters)
     * @throws IOException
     * @throws SQLException
     */
    void storeUserCredentials(String selector, String validator) throws SQLException, IOException;

    /**
     * Remove selector and validator of the user from the DB. The user must prompt
     * in the credentials again to login
     *
     * @throws SQLException
     */
    void userLogout() throws SQLException, IOException;
}
